"""Add payload to OTP codes

Revision ID: 1897f200c19d
Revises: a15195241aae
Create Date: 2026-07-15 22:31:47.488300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1897f200c19d'
down_revision: Union[str, Sequence[str], None] = 'a15195241aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('payload', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'payload')
    # ### end Alembic commands ###
