"""update skills to 5 categories

Revision ID: 1e9a04c5d036
Revises: e2a07955acf4
Create Date: 2026-07-18 01:27:26.501048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e9a04c5d036'
down_revision: Union[str, Sequence[str], None] = 'e2a07955acf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('professional_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('user_profiles', sa.Column('behavioural_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('user_profiles', sa.Column('ai_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('user_profiles', 'business_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('business_skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'ai_skills')
    op.drop_column('user_profiles', 'behavioural_skills')
    op.drop_column('user_profiles', 'professional_skills')
    # ### end Alembic commands ###
