"""fix missing columns

Revision ID: 8548504f2797
Revises: j1k2l3m4n5o6
Create Date: 2026-08-23 10:40:56.014893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8548504f2797'
down_revision: Union[str, Sequence[str], None] = 'j1k2l3m4n5o6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_three_b_results_assessment_id'), table_name='assessment_three_b_results')
    op.drop_table('assessment_three_b_results')
    op.add_column('assessment_task_analysis', sa.Column('next_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('assessment_task_analysis', sa.Column('auto_potential', sa.Integer(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('risk_level', sa.String(length=16), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('future_impact', sa.String(length=16), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('recommended_tools', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('assessment_task_analysis', sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.drop_column('assessment_task_analysis', 'cost_of_staying_as_is_json')
    op.drop_column('assessment_task_analysis', 'learning_implication_json')
    op.drop_column('assessment_task_analysis', 'pace_of_change')
    op.drop_column('assessment_task_analysis', 'action_status')
    op.drop_column('assessment_task_analysis', 'action_updated_at')
    op.drop_column('assessment_task_analysis', 'pipeline_run_id')
    op.drop_column('assessment_task_analysis', 'components_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_task_analysis', sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('assessment_task_analysis', sa.Column('pipeline_run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('action_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('action_status', sa.VARCHAR(length=32), server_default=sa.text("'NOT_STARTED'::character varying"), autoincrement=False, nullable=False))
    op.add_column('assessment_task_analysis', sa.Column('pace_of_change', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('learning_implication_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('cost_of_staying_as_is_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('assessment_task_analysis', 'components')
    op.drop_column('assessment_task_analysis', 'recommended_tools')
    op.drop_column('assessment_task_analysis', 'future_impact')
    op.drop_column('assessment_task_analysis', 'risk_level')
    op.drop_column('assessment_task_analysis', 'auto_potential')
    op.drop_column('assessment_task_analysis', 'next_actions')
    op.create_table('assessment_three_b_results',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pipeline_version', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('failed_stage', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hours_summary_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('assessment_three_b_results_assessment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_three_b_results_pkey'))
    )
    op.create_index(op.f('ix_assessment_three_b_results_assessment_id'), 'assessment_three_b_results', ['assessment_id'], unique=True)
    # ### end Alembic commands ###
