"""add salary_currency

Revision ID: 8a3e29025104
Revises: h9i0j1k2l3m4
Create Date: 2026-08-14 22:23:17.074317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3e29025104'
down_revision: Union[str, Sequence[str], None] = 'h9i0j1k2l3m4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assessment_task_analysis_task_id_key'), 'assessment_task_analysis', type_='unique')
    op.create_index(op.f('ix_assessment_task_analysis_task_id'), 'assessment_task_analysis', ['task_id'], unique=True)
    op.drop_constraint(op.f('career_intelligence_reports_assessment_id_key'), 'career_intelligence_reports', type_='unique')
    op.create_index(op.f('ix_career_intelligence_reports_assessment_id'), 'career_intelligence_reports', ['assessment_id'], unique=True)
    op.add_column('user_profiles', sa.Column('salary_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'salary_currency')
    op.drop_index(op.f('ix_career_intelligence_reports_assessment_id'), table_name='career_intelligence_reports')
    op.create_unique_constraint(op.f('career_intelligence_reports_assessment_id_key'), 'career_intelligence_reports', ['assessment_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_assessment_task_analysis_task_id'), table_name='assessment_task_analysis')
    op.create_unique_constraint(op.f('assessment_task_analysis_task_id_key'), 'assessment_task_analysis', ['task_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
