"""add 3b analysis ui fields

Revision ID: 93368b0ba1e2
Revises: cbda248d7171
Create Date: 2026-08-25 23:43:40.393807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93368b0ba1e2'
down_revision: Union[str, Sequence[str], None] = 'cbda248d7171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_task_analysis', sa.Column('importance', sa.String(length=32), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('feasibility_tier', sa.String(length=64), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('next_action', sa.Text(), nullable=True))
    op.alter_column('assessment_task_analysis', 'velocity',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_column('assessment_task_analysis', 'overall_feasibility')
    op.drop_column('assessment_task_analysis', 'next_action_summary')
    op.add_column('assessments', sa.Column('market_reality_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'market_reality_json')
    op.add_column('assessment_task_analysis', sa.Column('next_action_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('overall_feasibility', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.alter_column('assessment_task_analysis', 'velocity',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('assessment_task_analysis', 'next_action')
    op.drop_column('assessment_task_analysis', 'feasibility_tier')
    op.drop_column('assessment_task_analysis', 'importance')
    # ### end Alembic commands ###
