"""remove_location_daily_activities_rename_ai_skills

Revision ID: a12688da587f
Revises: e9890477ac7c
Create Date: 2026-08-02 00:56:20.491793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a12688da587f'
down_revision: Union[str, Sequence[str], None] = 'e9890477ac7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('career_paths_job_family_id_fkey', 'career_paths', type_='foreignkey')
    op.drop_constraint('career_paths_subsector_id_fkey', 'career_paths', type_='foreignkey')
    op.drop_constraint('specializations_job_family_id_fkey', 'specializations', type_='foreignkey')
    op.drop_column('specializations', 'job_family_id')
    op.drop_index(op.f('ix_job_families_name'), table_name='job_families')
    op.drop_index(op.f('ix_job_families_search_text'), table_name='job_families')
    op.drop_index(op.f('ix_job_families_slug'), table_name='job_families')
    op.drop_table('job_families')
    op.drop_index(op.f('ix_subsectors_name'), table_name='subsectors')
    op.drop_index(op.f('ix_subsectors_search_text'), table_name='subsectors')
    op.drop_index(op.f('ix_subsectors_slug'), table_name='subsectors')
    op.drop_table('subsectors')
    op.add_column('career_paths', sa.Column('department_id', sa.UUID(), nullable=False))
    op.add_column('career_paths', sa.Column('functional_domain_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_career_path_composite'), 'career_paths', type_='unique')
    op.create_unique_constraint('uq_career_path_composite', 'career_paths', ['sector_id', 'department_id', 'functional_domain_id', 'specialization_id'])
    op.create_foreign_key(None, 'career_paths', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'career_paths', 'functional_domains', ['functional_domain_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('career_paths', 'subsector_id')
    op.drop_column('career_paths', 'job_family_id')
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('departments_sector_id_name_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_sector_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'sectors', ['sector_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('functional_domains', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('functional_domains', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('functional_domains_department_id_name_key'), 'functional_domains', type_='unique')
    op.drop_constraint(op.f('functional_domains_department_id_fkey'), 'functional_domains', type_='foreignkey')
    op.create_foreign_key(None, 'functional_domains', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('specializations', 'functional_domain_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('specializations_functional_domain_id_fkey'), 'specializations', type_='foreignkey')
    op.create_foreign_key(None, 'specializations', 'functional_domains', ['functional_domain_id'], ['id'], ondelete='RESTRICT')
    op.add_column('user_profiles', sa.Column('digital_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.drop_column('user_profiles', 'daily_activities')
    op.drop_column('user_profiles', 'preferred_location')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'ai_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('ai_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('daily_activities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'digital_skills')
    op.drop_constraint(None, 'specializations', type_='foreignkey')
    op.create_foreign_key(op.f('specializations_functional_domain_id_fkey'), 'specializations', 'functional_domains', ['functional_domain_id'], ['id'], ondelete='CASCADE')
    op.alter_column('specializations', 'functional_domain_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'functional_domains', type_='foreignkey')
    op.create_foreign_key(op.f('functional_domains_department_id_fkey'), 'functional_domains', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('functional_domains_department_id_name_key'), 'functional_domains', ['department_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('functional_domains', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('functional_domains', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_sector_id_fkey'), 'departments', 'sectors', ['sector_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('departments_sector_id_name_key'), 'departments', ['sector_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('departments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('career_paths', sa.Column('job_family_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('career_paths', sa.Column('subsector_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'career_paths', type_='foreignkey')
    op.drop_constraint(None, 'career_paths', type_='foreignkey')
    op.create_foreign_key(op.f('career_paths_subsector_id_fkey'), 'career_paths', 'subsectors', ['subsector_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('career_paths_job_family_id_fkey'), 'career_paths', 'job_families', ['job_family_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_career_path_composite', 'career_paths', type_='unique')
    op.create_unique_constraint(op.f('uq_career_path_composite'), 'career_paths', ['sector_id', 'subsector_id', 'job_family_id', 'specialization_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('career_paths', 'functional_domain_id')
    op.drop_column('career_paths', 'department_id')
    op.create_table('subsectors',
    sa.Column('sector_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('subsectors_sector_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('subsectors_pkey'))
    )
    op.create_index(op.f('ix_subsectors_slug'), 'subsectors', ['slug'], unique=True)
    op.create_index(op.f('ix_subsectors_search_text'), 'subsectors', ['search_text'], unique=False)
    op.create_index(op.f('ix_subsectors_name'), 'subsectors', ['name'], unique=False)
    op.create_table('job_families',
    sa.Column('subsector_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subsector_id'], ['subsectors.id'], name=op.f('job_families_subsector_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_families_pkey'))
    )
    op.create_index(op.f('ix_job_families_slug'), 'job_families', ['slug'], unique=True)
    op.create_index(op.f('ix_job_families_search_text'), 'job_families', ['search_text'], unique=False)
    op.create_index(op.f('ix_job_families_name'), 'job_families', ['name'], unique=False)
    # ### end Alembic commands ###
