"""Add 3B analysis dense fields

Revision ID: cbda248d7171
Revises: 8548504f2797
Create Date: 2026-08-25 22:08:56.111867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbda248d7171'
down_revision: Union[str, Sequence[str], None] = '8548504f2797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_task_analysis', sa.Column('velocity', sa.String(length=32), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('velocity_note', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('overall_feasibility', sa.String(length=32), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('feasibility_note', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('human_capability', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('next_action_summary', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('learn_gap', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('learn_do', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('learn_dont', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('where_to_learn', sa.Text(), nullable=True))
    op.add_column('assessment_task_analysis', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_task_analysis', 'status')
    op.drop_column('assessment_task_analysis', 'where_to_learn')
    op.drop_column('assessment_task_analysis', 'learn_dont')
    op.drop_column('assessment_task_analysis', 'learn_do')
    op.drop_column('assessment_task_analysis', 'learn_gap')
    op.drop_column('assessment_task_analysis', 'next_action_summary')
    op.drop_column('assessment_task_analysis', 'human_capability')
    op.drop_column('assessment_task_analysis', 'feasibility_note')
    op.drop_column('assessment_task_analysis', 'overall_feasibility')
    op.drop_column('assessment_task_analysis', 'velocity_note')
    op.drop_column('assessment_task_analysis', 'velocity')
    # ### end Alembic commands ###
