"""Add UserProfile model

Revision ID: e2a07955acf4
Revises: 1897f200c19d
Create Date: 2026-07-17 23:29:27.145801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a07955acf4'
down_revision: Union[str, Sequence[str], None] = '1897f200c19d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('business_function', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('preferred_location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('business_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_frequency', sa.String(), nullable=False),
    sa.Column('ai_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_comfort_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
