"""Create Master Data Tables

Revision ID: e9890477ac7c
Revises: 0f2e43449e80
Create Date: 2026-07-22 23:22:14.122945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9890477ac7c'
down_revision: Union[str, Sequence[str], None] = '0f2e43449e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_terms',
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_glossary_terms_search_text', 'glossary_terms', ['search_text'], unique=False)
    op.create_index(op.f('ix_glossary_terms_slug'), 'glossary_terms', ['slug'], unique=True)
    op.create_index('ix_glossary_terms_term', 'glossary_terms', ['term'], unique=False)
    op.create_table('master_data_import_logs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('inserted_records', sa.Integer(), nullable=False),
    sa.Column('updated_records', sa.Integer(), nullable=False),
    sa.Column('skipped_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_data_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('taxonomy_version', sa.String(length=50), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('isco_code', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sectors_name', 'sectors', ['name'], unique=False)
    op.create_index('ix_sectors_search_text', 'sectors', ['search_text'], unique=False)
    op.create_index(op.f('ix_sectors_slug'), 'sectors', ['slug'], unique=True)
    op.create_table('subsectors',
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subsectors_name', 'subsectors', ['name'], unique=False)
    op.create_index('ix_subsectors_search_text', 'subsectors', ['search_text'], unique=False)
    op.create_index(op.f('ix_subsectors_slug'), 'subsectors', ['slug'], unique=True)
    op.create_table('job_families',
    sa.Column('subsector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subsector_id'], ['subsectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_families_name', 'job_families', ['name'], unique=False)
    op.create_index('ix_job_families_search_text', 'job_families', ['search_text'], unique=False)
    op.create_index(op.f('ix_job_families_slug'), 'job_families', ['slug'], unique=True)
    op.create_table('specializations',
    sa.Column('job_family_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('specialization_code', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('sector_code', sa.String(length=100), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('onet', sa.String(length=100), nullable=True),
    sa.Column('isco', sa.String(length=100), nullable=True),
    sa.Column('esco', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_specializations_name', 'specializations', ['name'], unique=False)
    op.create_index('ix_specializations_search_text', 'specializations', ['search_text'], unique=False)
    op.create_index(op.f('ix_specializations_slug'), 'specializations', ['slug'], unique=True)
    op.create_table('career_paths',
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('subsector_id', sa.UUID(), nullable=False),
    sa.Column('job_family_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subsector_id'], ['subsectors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'subsector_id', 'job_family_id', 'specialization_id', name='uq_career_path_composite')
    )
    op.create_table('job_titles',
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_titles_job_title', 'job_titles', ['job_title'], unique=False)
    op.create_index('ix_job_titles_search_text', 'job_titles', ['search_text'], unique=False)
    op.create_index(op.f('ix_job_titles_slug'), 'job_titles', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('specialization_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('proficiency_level', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.String(length=100), nullable=True),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('transferability', sa.String(length=255), nullable=True),
    sa.Column('certification', sa.String(length=255), nullable=True),
    sa.Column('ai_impact', sa.String(length=255), nullable=True),
    sa.Column('future_trajectory', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('search_text', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skills_search_text', 'skills', ['search_text'], unique=False)
    op.create_index('ix_skills_skill_name', 'skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index('ix_skills_skill_name', table_name='skills')
    op.drop_index('ix_skills_search_text', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_job_titles_slug'), table_name='job_titles')
    op.drop_index('ix_job_titles_search_text', table_name='job_titles')
    op.drop_index('ix_job_titles_job_title', table_name='job_titles')
    op.drop_table('job_titles')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_specializations_slug'), table_name='specializations')
    op.drop_index('ix_specializations_search_text', table_name='specializations')
    op.drop_index('ix_specializations_name', table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_job_families_slug'), table_name='job_families')
    op.drop_index('ix_job_families_search_text', table_name='job_families')
    op.drop_index('ix_job_families_name', table_name='job_families')
    op.drop_table('job_families')
    op.drop_index(op.f('ix_subsectors_slug'), table_name='subsectors')
    op.drop_index('ix_subsectors_search_text', table_name='subsectors')
    op.drop_index('ix_subsectors_name', table_name='subsectors')
    op.drop_table('subsectors')
    op.drop_index(op.f('ix_sectors_slug'), table_name='sectors')
    op.drop_index('ix_sectors_search_text', table_name='sectors')
    op.drop_index('ix_sectors_name', table_name='sectors')
    op.drop_table('sectors')
    op.drop_table('master_data_versions')
    op.drop_table('master_data_import_logs')
    op.drop_index('ix_glossary_terms_term', table_name='glossary_terms')
    op.drop_index(op.f('ix_glossary_terms_slug'), table_name='glossary_terms')
    op.drop_index('ix_glossary_terms_search_text', table_name='glossary_terms')
    op.drop_table('glossary_terms')
    # ### end Alembic commands ###
